---@type table
local opts = {
  -- set this to false to stop the theme from loading
  -- Whether to load the theme on startup.
  ---@type boolean | true
  load_theme = true,

  -- Path to the JSON file generated by matugen
  ---@type string | ""
  palette_path = "~/.config/matugen/themes/nvim-colors.json",
}

return opts
