---@type table
local cmds = {
  "CMakeGenerate",
  "CMakeClean",
  "CMakeBuild",
  "CMakeQuickBuild",
  "CMakeInstall",
  "CMakeStopExecutor",
  "CMakeStopRunner",
  "CMakeCloseExecutor",
  "CMakeCloseRunner",
  "CMakeOpenExecutor",
  "CMakeOpenRunner",
  "CMakeOpenCache",
  "CMakeRun",
  "CMakeQuickRun",
  "CMakeRunCurrentFile",
  "CMakeBuildCurrentFile",
  "CMakeLaunchArgs",
  "CMakeSelectBuildType",
  "CMakeSelectKit",
  "CMakeSelectConfigurePreset",
  "CMakeSelectBuildPreset",
  "CMakeSelectTestPreset",
  "CMakeSelectBuildTarget",
  "CMakeSelectLaunchTarget",
  "CMakeTargetSettings",
  "CMakeSettings",
  "CMakeSelectCwd",
  "CMakeSelectBuildDir",
  "CMakeRunTest",
  "CMakeQuickStart",
}

return cmds
