---@type AtlasConfig
local default = {
  pulls = {
    diff = {
      open_cmd = "AtlasDiff",
      layout = "inline",
      compact = true,
      explorer = {
        grouped = true,
        hidden = false,
        show_commits = true,
        width = 40,
        initial_focus = "explorer",
        ignore = { ".git/**", ".jj/**" },
      },
    },
  },
  issues = nil,
  keymaps = {
    ui = {
      help = "g?",
      close = "q",
      toggle_panel = "p",
      toggle_fold = "za",
      toggle_all_folds = "zA",
      previous_panel_tab = "<S-Tab>",
      next_panel_tab = "<Tab>",
      open_notifications = "N",
      notifications_mark_read = "r",
      notifications_mark_done = "d",
      notifications_refresh = "R",
      toggle_subscription = "gS",
      refresh = "r",
      refresh_view = "R",
      open_actions = "A",
      open_in_browser = "gx",
      copy_url = "Y",
      show_details = "K",
      search = "?",
    },
    pulls = {
      copy_id = "y",
      open_diff = "gd",
      checkout = "gc",
      review = {
        submit_review = "gs",
        toggle_layout = "t",
        toggle_compact = "f",
        next_hunk = "]h",
        previous_hunk = "[h",
        next_file = { "]f", "<Tab>" },
        previous_file = { "[f", "<S-Tab>" },
        toggle_file_reviewed = "-",
        toggle_commits = "gC",
        next_comment = "]c",
        previous_comment = "[c",
        next_note = "]n",
        previous_note = "[n",
        view_thread = "K",
        add_pending_comment = "c",
        add_comment = "C",
        add_note = "n",
        toggle_resolved = "x",
      },
      filter_status_open = "gpo",
      filter_status_merged = "gpm",
      filter_status_declined = "gpd",
    },
    issues = {
      copy_key = "y",
      transition_issue = "gs",
      change_assignee = "ga",
      change_reporter = "gr",
      edit_issue = "ge",
      create_issue = "c",
    },
  },
}
