---@type CamouflageConfig
local defaults = {
  enabled = true,
  debug = false,
  auto_enable = true,
  debounce_ms = 150,
  style = "stars",
  mask_char = "*",
  mask_length = nil,
  max_lines = 5000,
  hidden_text = "************************",
  highlight_group = "Comment",
  colors = nil, -- Custom colors override highlight_group: { foreground = '#808080', background = 'transparent', bold = false, italic = false }
  patterns = {
    { file_pattern = { ".env*", "*.env", ".envrc" }, parser = "env" },
    { file_pattern = { "*.sh" }, parser = "env" },
    { file_pattern = { "*.json" }, parser = "json" },
    { file_pattern = { "*.yaml", "*.yml" }, parser = "yaml" },
    { file_pattern = { "*.toml" }, parser = "toml" },
    { file_pattern = { "*.properties", "*.ini", "*.conf", "credentials" }, parser = "properties" },
    { file_pattern = { ".netrc", "_netrc" }, parser = "netrc" },
    { file_pattern = { "*.xml" }, parser = "xml" },
    { file_pattern = { "*.http" }, parser = "http" },
    { file_pattern = { "*.tf", "*.tfvars", "*.hcl" }, parser = "hcl" },
    {
      file_pattern = {
        "Dockerfile",
        "Dockerfile.*",
        "*.dockerfile",
        "Containerfile",
        "Containerfile.*",
      },
      parser = "dockerfile",
    },
  },
  parsers = {
    include_commented = true,
    env = { include_commented = true, include_export = true },
    json = { max_depth = 10 },
    yaml = { max_depth = 10 },
    xml = { max_depth = 10 },
    hcl = { max_depth = 10 },
    dockerfile = {},
  },
  integrations = {
    telescope = true,
    cmp = { disable_in_masked = true },
  },
  hooks = nil,
  yank = {
    default_register = "+",
    notify = true,
    auto_clear_seconds = 30,
    confirm = true,
    confirm_message = 'Copy value of "%s" to clipboard?',
  },
  reveal = {
    highlight_group = "CamouflageRevealed",
    notify = false,
    follow_cursor = false,
  },
  pwned = {
    enabled = true,
    auto_check = false,
    check_on_save = false,
    check_on_change = false,
    show_sign = true,
    show_virtual_text = true,
    show_line_highlight = true,
    sign_text = "!",
    sign_hl = "DiagnosticWarn",
    virtual_text_format = "PWNED (%s)",
    virtual_text_hl = "DiagnosticWarn",
    line_hl = "CamouflagePwned",
  },
  custom_patterns = {},
  audit = {
    ignore_patterns = { ".git", ".git/**", "node_modules", "node_modules/**" },
    max_files_per_chunk = 50,
    destination = "quickfix",
    open = true,
    notify = true,
  },
  policy = {
    enabled = true,
    default_action = "mask",
    terminal_path_ignores = {},
    rules = {},
  },
  checks = {
    badges = {
      position = "right_align",
      separator = " ",
      separator_hl = "Comment",
    },
    expiry = {
      enabled = true,
      show_threshold_seconds = 86400,
      warn_threshold_seconds = 3600,
      show_provider = true,
      refresh = {
        on_buf_enter = true,
        on_save = true,
        on_change = true,
        auto_interval = 60,
      },
      hl_valid = "Comment",
      hl_warning = "DiagnosticWarn",
      hl_expired = "DiagnosticError",
    },
    weak_secret = {
      enabled = true,
      min_length = 8,
      min_sensitive_length = 12,
      entropy_threshold = 3.0,
      sensitive_key_patterns = {
        "password",
        "passwd",
        "passphrase",
        "secret",
        "token",
        "api[_%-]*key",
        "access[_%-]*key",
        "private[_%-]*key",
        "client[_%-]*secret",
        "auth[_%-]*token",
        "credential",
      },
      ignored_key_patterns = {},
      ignored_value_patterns = {},
      common_values = {
        "password",
        "password1",
        "password123",
        "secret",
        "secret123",
        "changeme",
        "changeit",
        "admin",
        "default",
        "test",
        "testing",
        "demo",
        "dummy",
        "qwerty",
        "letmein",
        "welcome",
        "hunter2",
      },
      show_sign = false,
      sign_text = "!",
      sign_hl = "DiagnosticWarn",
      show_virtual_text = true,
      virtual_text_format = "[weak: %s]",
      virtual_text_hl = "DiagnosticWarn",
      line_hl = nil,
    },
  },
  project_config = {
    enabled = true,
    filename = ".camouflage.yaml",
    notify = true,
    secure = false,
    watch_enabled = true,
    watch_backend = "auto",
    watch_debounce_ms = 200,
    max_watched_roots = 10,
    notify_on_reload = false,
  },
}
