-- Deterministic JSON field ordering for schema v2.

return {
  ["$"] = {
    "format",
    "schema_version",
    "units",
    "metadata",
    "settings",
    "rooms",
    "doors",
    "furniture",
    "custom_templates",
    "extensions",
  },
  ["$.metadata"] = { "name", "notes" },
  ["$.settings"] = {
    "grid_mm",
    "fine_step_mm",
    "normal_step_mm",
    "coarse_step_mm",
    "default_door_width_mm",
  },
  ["$.rooms[]"] = { "id", "name", "color", "origin_mm", "footprint" },
  ["$.rooms[].footprint"] = { "kind", "parts" },
  ["$.rooms[].footprint.parts[]"] = { "id", "origin_mm", "size_mm" },
  ["$.doors[]"] = {
    "id",
    "kind",
    "room_id",
    "connects_to_room_id",
    "part_id",
    "side",
    "offset_mm",
    "width_mm",
    "hinge",
    "opens_into",
    "open_angle_deg",
  },
  ["$.furniture[]"] = {
    "id",
    "room_id",
    "template_id",
    "name",
    "color",
    "category",
    "position_mm",
    "anchor2_mm",
    "footprint",
    "height_mm",
    "rotation_deg",
  },
  ["$.furniture[].footprint"] = { "kind", "parts" },
  ["$.furniture[].footprint.parts[]"] = { "id", "origin_mm", "size_mm" },
  ["$.custom_templates[]"] = {
    "id",
    "name",
    "category",
    "default_footprint",
    "default_anchor2_mm",
    "default_height_mm",
  },
  ["$.custom_templates[].default_footprint"] = { "kind", "parts" },
  ["$.custom_templates[].default_footprint.parts[]"] = { "id", "origin_mm", "size_mm" },
}
